### ISSUE TITLE
Onboarding: Gutenberg event not fired on save

### ISSUE THREAD

**Issue by joshuatf** [woocommerce/woocommerce-admin#3155]
**Describe the bug**
For the onboarding task script used for the homepage, I'm getting the following error when loading the editor:

`wp.domReady is not a function`

**To Reproduce**

1. WP 5.2.4
2. Delete your homepage if necessary.
3. Go to the "Customize Appearance" task.
4. Create a homepage.
5.  Note the console errors and return to task list notice not showing.

**Expected behavior**
Expected no errors and the task list return notice to show.

**Screenshots**
<img width="785" alt="Screen Shot 2019-11-01 at 1 01 11 PM" src="https://user-images.githubusercontent.com/10561050/68003447-61fa2700-fca8-11e9-867f-9e4f32b6da6d.png">

**Comment by justinshreve** [comment]
@joshuatf I can't seem to reproduce this with `5.2.4`. I see "Your homepage was published. Continue setup." as expected.

While testing this on 5.3, I did notice the notification no longer works with 5.3's updated handling. I'll log that in a separate issue.

**Comment by justinshreve** [comment]
@joshuatf Does this https://github.com/woocommerce/woocommerce-admin/compare/test/wp-dom-ready fix the issue for you on 5.2.4?

**Comment by joshuatf** [comment]
>@joshuatf Does this https://github.com/woocommerce/woocommerce-admin/compare/test/wp-dom-ready fix the issue for you on 5.2.4?

@justinshreve That does fix the `domReady` issue in 5.2.4 and code is executed inside, but then I'm hit with `Cannot read property 'select' of undefined`.

<img width="607" alt="Screen Shot 2019-11-06 at 3 16 06 PM" src="https://user-images.githubusercontent.com/10561050/68276821-cfdb8f80-00a8-11ea-8fd0-c1c029f622b8.png">

After adding `wp-data` as a dependency to `wp_enqueue_script` fixes that but `select( 'core/editor' ).getCurrentPostType()` returns undefined so the rest of the code is never executed.
